# Generated by Django 5.0.1 on 2024-02-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_cust', '0002_alter_customer_email_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
